language: cpp

matrix:
  include:
    # Linux (gcc)
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      compiler: gcc

      install:
        - docker build -t ubuntu - < Dockerfile

      script:
        - docker run --rm -v $(pwd):/starviewer -e CC -e CXX ubuntu qmake
        - docker run --rm -v $(pwd):/starviewer -e CC -e CXX ubuntu make -j3
        - docker run --rm -v $(pwd):/starviewer -e TRAVIS_OS_NAME -w /starviewer/starviewer/tests/auto ubuntu
            sh -c 'xvfb-run -s "-screen 0 640x480x24" ./autotests -silent'

    # Linux (clang)
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      compiler: clang

      install:
        - docker build -t ubuntu - < Dockerfile

      script:
        - docker run --rm -v $(pwd):/starviewer -e CC -e CXX ubuntu qmake -spec linux-clang
        - docker run --rm -v $(pwd):/starviewer -e CC -e CXX ubuntu make -j3
        - docker run --rm -v $(pwd):/starviewer -e TRAVIS_OS_NAME -w /starviewer/starviewer/tests/auto ubuntu
            sh -c 'xvfb-run -s "-screen 0 640x480x24" ./autotests -silent'

    # Mac (clang)
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
      - SDK_INSTALL_PREFIX="$HOME/sdk-0.15/usr/local"
      - DYLD_LIBRARY_PATH="$SDK_INSTALL_PREFIX/lib"
      - DYLD_FRAMEWORK_PATH="/usr/local/opt/qt/lib"

      before_install:
        - brew update > /dev/null
        - echo "Install Qt 5.9."
        - cp qt.rb $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
        - brew install qt
        - chmod -R 755 /usr/local/opt/qt/*

      install:
        - QTDIR="/usr/local/opt/qt"
        - PATH="$QTDIR/bin:$PATH"
        - LDFLAGS=-L$QTDIR/lib
        - CPPFLAGS=-I$QTDIR/include
        - wget -nv --directory-prefix=$HOME http://trueta.udg.edu/apt/macos/devel/0.15/starviewer-sdk-macos-0.15-3.tar.xz
        - mkdir ~/sdk-0.15
        - tar xf ~/starviewer-sdk-macos-0.15-3.tar.xz -C ~/sdk-0.15

      script:
        - cd starviewer
        - qmake
        - make -j3 | sed 's/\/Applications\/Xcode\.app\/Contents\/Developer/[xcode]/g' | sed -E 's/\/(Users|home)\/travis\/sdk-0.15/[sdk]/g'
        - cd tests/auto
        - ./autotests -silent
