language: cpp

os:
  - linux
  - osx

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

env:
  global:
    - SDK_INSTALL_PREFIX="$HOME/uroot/usr/local"
    - LD_LIBRARY_PATH="$SDK_INSTALL_PREFIX/lib:$SDK_INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-add-repository -y ppa:beineri/opt-qt542-trusty                           &&
      sudo apt-get update -qq                                                           &&
      sudo apt-get install -qq qt54base qt54quick1 qt54tools qt54webkit qt54xmlpatterns &&
      sudo apt-get install -qq liblog4cxx10 liblog4cxx10-dev                            &&
      sudo apt-get install -qq libwrap0 libwrap0-dev                                    ;
    else
      brew update > /dev/null                                                      &&
      cd `brew --prefix`                                                           &&
      echo "Install Qt 5.4."                                                       &&
      git checkout 00e46351980ad915424aad9316abffc19936809c Library/Formula/qt5.rb &&
      cd -                                                                         &&
      brew install qt5                                                             &&
      chmod -R 755 /usr/local/opt/qt5/*                                            &&
      brew install log4cxx                                                         ;
    fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      . /opt/qt54/bin/qt54-env.sh                                                                                  &&
      wget --directory-prefix=$HOME http://trueta.udg.edu/apt/ubuntu/devel/0.13/Starviewer-sdk-linux-0.13-0.tar.xz &&
      mkdir ~/uroot                                                                                                &&
      tar xf ~/Starviewer-sdk-linux-0.13-0.tar.xz -C ~/uroot                                                       ;
    else
      QTDIR="/usr/local/opt/qt5"                                                                               &&
      PATH="$QTDIR/bin:$PATH"                                                                                  &&
      LDFLAGS=-L$QTDIR/lib                                                                                     &&
      CPPFLAGS=-I$QTDIR/include                                                                                &&
      wget --directory-prefix=$HOME http://trueta.udg.edu/apt/macosx/devel/Starviewer-sdk-macosx-0.13-0.tar.xz &&
      tar xf ~/Starviewer-sdk-macosx-0.13-0.tar.xz -C /usr/local --strip-components 2                          ;
    fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0         &&
      sh -e /etc/init.d/xvfb start ;
    fi

script:
  - cd starviewer
  - qmake
  - make -j3
  - cd tests/auto
  - ./autotests -silent
