version: 0.14-{build}-{branch}

environment:
  SDK_INSTALL_PREFIX: C:\

  matrix:
  - BITS: 32
    QTDIR: C:\Qt\5.6\msvc2015
    ARCH: x86
  - BITS: 64
    QTDIR: C:\Qt\5.6\msvc2015_64
    ARCH: amd64

# Uncomment to enable RDP
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- ps: |
    # Setup precompiled SDK

    $source = "http://trueta.udg.edu/apt/windows/devel/0.14/starviewer-sdk-win$env:BITS-0.14-5.7z"
    $destination = "c:\starviewer-sdk-win$env:BITS-0.14-5.7z"
    Invoke-WebRequest $source -OutFile $destination

    7z x $destination -oc:\ > 7z-output.txt

    $env:PATH = "$env:QTDIR\bin;c:\vtk\7.0.0\bin;c:\gdcm\2.6.4\bin;c:\ThreadWeaver\5.3.0\bin;$env:PATH"


    # Setup jom

    $source = "http://ftp.fau.de/qtproject/official_releases/jom/jom_1_1_0.zip"
    $destination = "c:\jom.zip"
    Invoke-WebRequest $source -OutFile $destination

    7z x $destination -oc:\jom\

    $env:PATH = "$env:PATH;c:\jom"

build_script:
- cmd: |
    call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
    cd starviewer
    qmake
    jom -j2

test_script:
- ps: |
    cd tests\auto
    .\autotests -saveOutputToDir results -xunitxml

    cd results
    $wc = New-Object 'System.Net.WebClient'
    ls | % {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.Name))
        $content = cat $_
        if ($content -Match 'result="fail"') {
            echo $content "------------"
        }
    }

    if ($LASTEXITCODE -ne 0) {
        Add-AppveyorMessage "$LASTEXITCODE test(s) failed" -Category Error
        throw "$LASTEXITCODE test(s) failed"
    }
    else {
        Add-AppveyorMessage "All tests OK"
    }
